### ISSUE TITLE
Load icons via HTTPS

### ISSUE THREAD

**Issue by rettinghaus** [hbz/lobid-gnd#195] opened 2019-04-09 14:29 UTC
For proper HTTPS load graphics/icons from other sites over HTTPS or cache them locally. 

(BTW the `favicon.ico` from www.deutsche-digitale-bibliothek.de is gone.)

**Comment by acka47** [comment] 2019-04-10 09:23
As the icon URLs are coming from the EntityFacts data we use for lobid-gnd, I opened an issue in the (password-protected) GND Jira: https://jira.dnb.de/browse/GND-97. I will leave this issue open until the problem is fixed upstream.

**Comment by acka47** [comment] 2019-04-10 09:24
And thanks for the report, @rettinghaus!

**Comment by dr0i** [comment] 2020-09-01 09:41
This is fixed with hbz/lobid#421.
Closing.

**Closed by dr0i** 2020-09-01 09:41 UTC
Labels: upstream
