### ISSUE TITLE
Entry missing

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#258] opened 2020-07-29 09:33 UTC
@RobRoth reported via Twitter DM:

> Ist es normal, dass Einträge in der GND eine Woche und länger brauchen, bis die via OAI-PMH bei Euch landen? Es geht aktuell um diese Einrichtung: http://d-nb.info/gnd/1214378811 Der Eintrag wurde am 23.07 (also letzte Woche Donnerstag) vorgenommen. Via Lobid ist er aber leider noch nicht auffindbar, was mich etwas irritiert.

Obviously, there are problems with the updates. I can not check whether this is a general problem, though, because I can not search per day in `describedBy.dateModified`, see https://github.com/hbz/lobid-gnd/issues/257#issuecomment-665553771

**Comment by RobRoth** [comment] 2020-07-29 09:47
Thx! I didn't thought about opening a request in here, because I hoped that it is only a smaller issue... But good to see, that it's put on track now.

**Comment by acka47** [comment] 2020-07-30 13:47
Whoop, there it is (on staging): http://stage.lobid.org/gnd/1214378811 Will be there when deployed.

**Comment by dr0i** [comment] 2020-07-30 15:52
Issue is solved with #257.
Analysis: no gnd-ID `1214378811` could be found in the logs. Looking into the logs revealed some days with (near) zero bytes of daily OAI-PMH updates (2020-07-23 one of them) . Resolving #257, getting an update of July's data, the ID could be found in the logs.

This issue made us aware of the need of scripts which would alert us if data is unexpected low in bytes, or/and implement and automatical fallback (retry of getting and indexing), thus opened #260.

Thx @RobRoth.

Closing this issue.

**Comment by IronPan10111** [comment] 2020-10-05 10:36
Hi folks. The problem has reappeared. For whatever reason, the entry has been kicked out of the API again (as you can see here: [](https://lobid.org/gnd/1214378811) ). I am afraid that this does not only affect this one entry.

**Comment by acka47** [comment] 2020-10-05 10:46
Thanks for letting us know, @IronPan10111. Reopening.

**Comment by fsteeg** [comment] 2020-10-05 12:25
Restored in production: https://lobid.org/gnd/1214378811

The cause for this was that when I reindexed (without conversion) for https://github.com/hbz/lobid-gnd/pull/268, I missed the updates manually created by @dr0i after fixing this issue here in the first place. For the next full conversion plus indexing, the fix will be used automatically, so this should not happen again.

**Comment by IronPan10111** [comment] 2020-10-05 14:19
From my point of view it looks good! :smiley: Thx!

**Closed** 2020-10-06 06:40 UTC
Labels: bug
