### ISSUE TITLE
Field search is broken

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#32] opened 2017-10-13 11:49 UTC
See e.g. http://test.lobid.org/gnd/search?q=*+AND+type:%22CorporateBody%22 where all GND resources are listed with those on top that contain "type" and something similar to "CorporateBody".

**Comment by acka47** [comment] 2017-10-16 09:04
Field search is not broken per see as I just learned responding to a question on twitter: https://twitter.com/herr_tu/status/919848128936849409

**Comment by fsteeg** [comment] 2017-10-17 09:00
Deployed to test:

http://test.lobid.org/gnd/search?q=*+AND+type:%22CorporateBody%22
http://test.lobid.org/gnd/search?q=preferredName%3A%22Heine%2C+Heinrich%22

Root cause was a bad fix for https://github.com/hbz/lobid-gnd/issues/20, which caused the full query string to be applied to the `preferredName` field, resulting in hits with `type` in their name for the sample query above. This field query was only part of the complete query, so sometimes results were good.

**Comment by acka47** [comment] 2017-10-17 09:07
+1 (But the order still changes when using a filter, see #28. Will have to address this at a later point.)

**Comment by ChristophEwertowski** [comment] 2017-10-17 09:40
+1 Assigning it back to fsteeg for opening a pull request with the right, non-WIP-branch and assigning it to @dr0i.

**Closed** 2017-10-17 12:27 UTC
Labels: bug, deploy
