### ISSUE TITLE
Index dates as such in Elasticsearch

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-gnd#150] opened 2018-08-24 10:36 UTC
...so that we can create timeline visualizations in Kibana. Similar to https://github.com/hbz/lobid-resources/issues/869.

**Comment by fsteeg** [comment] 2018-08-24 11:17
Duplicate of https://github.com/hbz/lobid-gnd/issues/140 (I commented there).

**Closed by fsteeg** 2018-08-24 11:17 UTC
