### ISSUE TITLE
"Siehe auch" contains duplicated labels, value not shown

### ISSUE THREAD

**Issue by annainfo** [hbz/lobid-gnd#235] opened 2019-09-17 13:18 UTC
https://test.lobid.org/gnd/118049240
(https://web.archive.org/save/https://test.lobid.org/gnd/118049240)

Label "International Standard Name Identifier (ISNI)" appears twice, two others in between, links differ:
- http://www.isni.org/0000000108680707
- http://isni.org/isni/0000000108680707
(same ISNI, different prefix)

Label "Deutsche Nationalbibliothek (DNB)" appears 4 times, no other in between, links differ:
- http://d-nb.info/gnd/160623731
- http://d-nb.info/gnd/160327342
- http://d-nb.info/gnd/157780503
- http://d-nb.info/gnd/118049240/about (sic!)

**Comment by acka47** [comment] 2019-09-18 07:38
Duplicate of #203. As said there, this has to be fixed by DNB in the GND RDF and I already opened an issue there. Closing.

**Closed by acka47** 2019-09-18 07:38 UTC
Labels: upstream
