### ISSUE TITLE
Index reconfiguring for better kibana-stats

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-gnd#140] opened 2018-07-06 11:16 UTC
Result of #66.
To create nice stats the more index fields be typed as `number` (or even more accurate: `date`) the better.
See [ES-docs for possible types](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/mapping-types.html). There is no need to change the format of the values e.g. of the field `dateOfBirth` -  it seems to be sufficient to just configure the index to:

> ~"type": "date_range"~ "type": "date", 
> "format": "yyyy-MM-dd"

(https://www.elastic.co/guide/en/elasticsearch/reference/5.6/date.html)

I would say that all fields starting with `date` are reasonable ~`date_range`~  `date` candidates.

**Comment by fsteeg** [comment] 2018-08-24 11:16
The problem is that many dates in lobid-gnd have non-date values (like `[19XX]`, `[?]`, `[XXXX]`, `[20.]` etc., see `dateOfBirth` aggregation in http://lobid.org/gnd/search?q=*&format=json), which would cause indexing errors if they were set as date (I guess).

**Comment by dr0i** [comment] 2018-08-28 13:10
Correct, it would result in `MapperParsingException`, so we have to make sure that the value of `date` is valid. See https://github.com/hbz/lobid-resources/pull/871 for details how this was done for lobid-resources.

**Comment by acka47** [comment] 2020-12-03 15:37
Closing.

**Closed by acka47** 2020-12-03 15:37 UTC
